name: IaC Security Scan Project 2

on:
  push:
    branches:
      - main

jobs:
  iac-scan:
    name: IaC Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Terraform files
        run: |
          echo "Terraform files:"
          find . -name "*.tf" -type f -print

      - name: Run Trivy IaC scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'